# Docker image for DHCP server

DOCKER_DHCP_SERVER_STEM = docker-dhcp-server
DOCKER_DHCP_SERVER = $(DOCKER_DHCP_SERVER_STEM).gz
DOCKER_DHCP_SERVER_DBG = $(DOCKER_DHCP_SERVER_STEM)-$(DBG_IMAGE_MARK).gz

$(DOCKER_DHCP_SERVER)_PATH = $(DOCKERS_PATH)/$(DOCKER_DHCP_SERVER_STEM)

$(DOCKER_DHCP_SERVER)_DEPENDS = $(SONIC_LINKMGRD) $(LIBSWSSCOMMON) $(LIBHIREDIS)
$(DOCKER_DHCP_SERVER)_DBG_DEPENDS = $($(DOCKER_CONFIG_ENGINE_BULLSEYE)_DBG_DEPENDS)
$(DOCKER_DHCP_SERVER)_DBG_DEPENDS += $(SONIC_LINKMGRD_DBG) $(LIBSWSSCOMMON_DBG) $(LIBHIREDIS_DBG)

$(DOCKER_DHCP_SERVER)_DBG_IMAGE_PACKAGES = $($(DOCKER_CONFIG_ENGINE_BULLSEYE)_DBG_IMAGE_PACKAGES)

$(DOCKER_DHCP_SERVER)_LOAD_DOCKERS = $(DOCKER_CONFIG_ENGINE_BULLSEYE)

$(DOCKER_DHCP_SERVER)_VERSION = 1.0.0
$(DOCKER_DHCP_SERVER)_PACKAGE_NAME = dhcp-server
$(DOCKER_DHCP_SERVER)_WARM_SHUTDOWN_BEFORE = swss
$(DOCKER_DHCP_SERVER)_FAST_SHUTDOWN_BEFORE = swss

ifeq ($(INCLUDE_DHCP_SERVER), y)
SONIC_DOCKER_IMAGES += $(DOCKER_DHCP_SERVER)
SONIC_INSTALL_DOCKER_IMAGES += $(DOCKER_DHCP_SERVER)
endif

ifeq ($(INCLUDE_DHCP_SERVER), y)
SONIC_DOCKER_DBG_IMAGES += $(DOCKER_DHCP_SERVER_DBG)
SONIC_INSTALL_DOCKER_DBG_IMAGES += $(DOCKER_DHCP_SERVER_DBG)
endif

$(DOCKER_DHCP_SERVER)_CONTAINER_NAME = dhcp_server
$(DOCKER_DHCP_SERVER)_RUN_OPT += --privileged -t
$(DOCKER_DHCP_SERVER)_RUN_OPT += -v /etc/sonic:/etc/sonic:ro
$(DOCKER_DHCP_SERVER)_RUN_OPT += -v /etc/timezone:/etc/timezone:ro 
$(DOCKER_DHCP_SERVER)_RUN_OPT += -v /var/run/redis:/redis_sock:ro
$(DOCKER_DHCP_SERVER)_FILES += $(SUPERVISOR_PROC_EXIT_LISTENER_SCRIPT)
